parameters:
    fsc.rest.factory.atom_link.rel_prefix: ''

services:
    fsc.rest.factory.atom_link:
        class: FSC\RestBundle\REST\AtomLinkFactory
        arguments:
          - %fsc.rest.factory.atom_link.rel_prefix%

    fsc.rest.resource.abstract:
        abstract: true
        class: FSC\RestBundle\REST\AbstractResource
        arguments:
            - @router
            - @fsc.rest.normalizer.form
            - @form.factory
            - @fsc.rest.factory.atom_link
            - @service_container

    fsc.rest.resource.abstract_doctrine:
        abstract: true
        parent: fsc.rest.resource.abstract
        calls:
          - [ setEntityManager, [ @doctrine.orm.entity_manager ] ]
